---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.giantswarm.io
  resources:
  - organizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.giantswarm.io
  resources:
  - organizations/finalizers
  verbs:
  - update
- apiGroups:
  - security.giantswarm.io
  resources:
  - organizations/status
  verbs:
  - get
  - patch
  - update
