{{- if .Values.serviceMonitor.scrapeAuth.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "resource.metricsServiceAccount.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "resource.metricsServiceAccount.name"  . }}
{{- end }}
