apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.pod.ports.http }}
      protocol: TCP
      targetPort: http
    - name: metrics
      port: {{ .Values.pod.ports.metrics }}
      protocol: TCP
      targetPort: metrics
  selector:
    {{- include "labels.selector" . | nindent 4 }}
