image:
  name: "giantswarm/organization-operator"
  tag: "[[ .Version ]]"
pod:
  user:
    id: 1000
  group:
    id: 1000
project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
registry:
  domain: docker.io
  pullSecret:
    dockerConfigJSON: ""

# Add seccomp to pod security context
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
securityContext:
  seccompProfile:
    type: RuntimeDefault
