image:
  name: "giantswarm/organization-operator"
pod:
  user:
    id: 1000
  group:
    id: 1000
resyncPeriod: "5m"
registry:
  domain: gsoci.azurecr.io

# Add seccomp to pod security context
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
securityContext:
  seccompProfile:
    type: RuntimeDefault

serviceMonitor:
  enabled: true
  # -- (duration) Prometheus scrape interval.
  interval: "60s"
  # -- (duration) Prometheus scrape timeout.
  scrapeTimeout: "45s"

  scrapeAuth:
    # -- (boolean) Whether scrape requests to the metrics endpoint must authenticate first.
    enabled: true

    # -- (string) The name of the new or existing service account to use for authentication.
    serviceAccountName: ""

    # -- (boolean) Whether this chart should create the service account for scraping metrics.
    createServiceAccount: true

  tls:
    # --- (boolean) Whether scrape connections should use TLS.
    enabled: true
    # --- (string) The name of the issuer to use to create the TLS certificate.
    issuerName: selfsigned-giantswarm
    # --- (string) The name of the secret that contains the TLS certificate and private key.
    secretName: organization-operator-tls

global:
  podSecurityStandards:
    enforced: false

# Metrics port
ports:
  metrics: 8080

ciliumNetworkPolicy:
  enabled: false
