image:
  name: "giantswarm/organization-operator"
pod:
  user:
    id: 1000
  group:
    id: 1000
resyncPeriod: "5m"
registry:
  domain: gsoci.azurecr.io

# Add seccomp to pod security context
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
securityContext:
  seccompProfile:
    type: RuntimeDefault

serviceMonitor:
  enabled: true
  # -- (duration) Prometheus scrape interval.
  interval: "60s"
  # -- (duration) Prometheus scrape timeout.
  scrapeTimeout: "45s"

global:
  podSecurityStandards:
    enforced: false

# Metrics port
ports:
  metrics: 8080

ciliumNetworkPolicy:
  enabled: true

